[build]
  command = "npm run build" # Ou "npm install" caso não tenha build
  publish = "." # Diretório de publicação
  functions = "functions"  # Diretório das funções Lambda

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
